version: "3.2"
services:
# disabled: we do not have a service to extract and push yet
#  pushgateway:
#    image: prom/pushgateway:v1.4.2
#    container_name: pushgateway
#    ports:
#      - "9091:9091"
#    networks:
#      - monitoring_internal
  prometheus:
    image: quay.io/prometheus/prometheus:v2.32.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring_internal
    command:
      - --config.file=/etc/prometheus/config.yml

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring_internal

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

networks:
  monitoring_internal:
    name: monitoring_internal
#    enable_ipv6: true
