{
 "title": "Windows",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_core",
    "query": {
     "query": "label_values(windows_cpu_time_total,core)"
    }
   },
   {
    "name": "selected_nic",
    "query": {
     "query": "label_values(windows_net_bytes_received_total,nic)"
    }
   },
   {
    "name": "selected_volume",
    "query": {
     "query": "label_values(windows_logical_disk_read_bytes_total,volume)"
    }
   },
   {
    "name": "selected_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_cpu_time_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DCS FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Frame/sec" } },
   "targets": [
    {
     "expr": "dcs_fps{instance=\"$selected_instance\"}",
     "legendFormat": "fps"
    },
    {
     "expr": "avg_over_time(dcs_fps{instance=\"$selected_instance\"}[$__range])",
     "legendFormat": "average fps"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{instance=\"$selected_instance\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{instance=\"$selected_instance\"}",
     "legendFormat": "usage ratio"
    }
   ]
  },
  {
   "title": "GPU Memory ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{instance=\"$selected_instance\"}",
     "legendFormat": "usage ratio"
    }
   ]
  },
  {
   "title": "Graphics clock",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{instance=\"$selected_instance\"}",
     "legendFormat": "clock"
    }
   ]
  },
  {
   "title": "Video clock",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{instance=\"$selected_instance\"}",
     "legendFormat": "clock"
    }
   ]
  },
  {
   "title": "SM clock",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{instance=\"$selected_instance\"}",
     "legendFormat": "clock"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{instance=\"$selected_instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "nvidia_smi_memory_free_bytes{instance=\"$selected_instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{instance=\"$selected_instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "CPU time - overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU overall",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=\"$selected_instance\"}[5s]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "CPU time - per core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Core: $selected_core",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
   "repeat": "selected_core",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(windows_cpu_time_total{core=\"$selected_core\",mode=~\"dpc|idle|interrupt|privileged|user\",instance=\"$selected_instance\"}[5s])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "windows_memory_available_bytes{job=\"windows_exporter\", instance=\"$selected_instance\"}",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Storage - Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "$selected_nic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
   "repeat": "selected_nic",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{nic=\"$selected_nic\",instance=\"$selected_instance\"}[$__interval])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{nic=\"$selected_nic\",instance=\"$selected_instance\"}[$__interval])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "$selected_volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "repeat": "selected_volume",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{job=\"windows_exporter\",volume=\"$selected_volume\",instance=\"$selected_instance\"}[$__interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{job=\"windows_exporter\",volume=\"$selected_volume\",instance=\"$selected_instance\"}[$__interval])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}